root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/worker ./cmd/worker/"
bin = "tmp/worker"
include_ext = ["go"]
exclude_dir = ["tmp", "migrations", "seeds"]
delay = 1000

[log]
time = false

[misc]
clean_on_exit = true
